# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e3363b698bb1083b507335140939ff05d9085b4ab2f70ac9f0467734bbd493f6dbe622d5637dc4715f6fa1e5079802a59666b953884e7d3c18b3af2d7f7f5d

test:
  secret_key_base: ccb60824ef53f4293cfa8a98f510f961076db3b509b03cd962fa023b73fd3f29e2a6098551d061920c2b6b4c73bd6c5953047d9b9db288fd08b2840444d4b2a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
